services:
  app:
    build: .
    container_name: lv-product-inventory-app
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    ports:
      - "8080:80"
    volumes:
      - "./.env:/var/www/html/.env:rw"
    networks:
      - warehouse-network

  db:
    image: mysql:8.0
    container_name: lv-product-inventory-db
    restart: unless-stopped
    ports:
      - "${DOCKER_DB_PORT}:3306"
    environment:
      MYSQL_DATABASE: lv_warehouse_inventory_ms
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: warehouse_user
      MYSQL_PASSWORD: secret
    volumes:
      - db-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

    networks:
      - warehouse-network

  redis:
    image: redis:alpine
    container_name: lv-product-inventory-redis
    restart: unless-stopped
    tty: true
    ports:
      - "${DOCKER_APP_PORT}:80"
      - "${DOCKER_APP_SSL_PORT}:443"
    volumes:
      - ./:/var/www
      - ./.docker/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - warehouse-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: unless-stopped
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: root
    depends_on:
      - db
    networks:
      - warehouse-network

#Docker Networks
networks:
  warehouse-network:

#Volumes
volumes:
  db-data:
